CREATE TABLE [dbo].[圖片](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[上傳用戶_FK] [int] NULL,
	[路徑] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_圖片] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]