CREATE TABLE [dbo].[提問](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[問題] [nvarchar](max) NOT NULL,
	[回答] [nvarchar](max) NOT NULL,
	[提問用戶_FK] [int] NULL,
 CONSTRAINT [PK_提問] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]