CREATE TABLE [dbo].[文章Hashtag](
	[文章_FK] [int] NOT NULL,
	[Hashtag_FK] [int] NOT NULL,
 CONSTRAINT [PK_文章Hashtag] PRIMARY KEY CLUSTERED 
(
	[文章_FK] ASC,
	[Hashtag_FK] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]