CREATE TABLE [dbo].[用戶Hashtag](
	[用戶_FK] [int] NOT NULL,
	[Hashtag_FK] [int] NOT NULL,
 CONSTRAINT [PK_用戶Hashtag] PRIMARY KEY CLUSTERED 
(
	[用戶_FK] ASC,
	[Hashtag_FK] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]