CREATE TABLE [dbo].[用戶Favorite](
	[收藏文章_FK] [int] NOT NULL,
	[用戶_FK] [int] NOT NULL,
 CONSTRAINT [PK_用戶Favorite] PRIMARY KEY CLUSTERED 
(
	[收藏文章_FK] ASC,
	[用戶_FK] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]