CREATE TABLE [dbo].[評級](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[分數] [int] NOT NULL,
	[評分用戶_FK] [int] NULL,
	[文章_FK] [int] NULL,
	[評論] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_評級] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]