//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoGoShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class 文章
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 文章()
        {
            this.旅程包_link = new HashSet<旅程包_link>();
            this.評級 = new HashSet<評級>();
            this.Hashtag = new HashSet<Hashtag>();
            this.用戶 = new HashSet<用戶>();
        }
    
        public int Id { get; set; }
        public string 標題 { get; set; }
        public int 作者用戶_FK { get; set; }
        public string 內容 { get; set; }
        public System.DateTime 日期起始 { get; set; }
        public System.DateTime 日期結束 { get; set; }
        public Nullable<int> 圖片_FK { get; set; }
        public string 地點 { get; set; }
        public int 接待人數 { get; set; }
        public string 類型 { get; set; }
        public int 點數 { get; set; }
        public Nullable<System.DateTime> 文章註冊時間 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<旅程包_link> 旅程包_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<評級> 評級 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hashtag> Hashtag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<用戶> 用戶 { get; set; }
    }
}
