//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoGoShare
{
    using System;
    using System.Collections.Generic;
    
    public partial class 用戶
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 用戶()
        {
            this.旅程包 = new HashSet<旅程包>();
            this.提問 = new HashSet<提問>();
            this.評級 = new HashSet<評級>();
            this.圖片 = new HashSet<圖片>();
            this.文章 = new HashSet<文章>();
            this.Hashtag = new HashSet<Hashtag>();
        }
    
        public int Id { get; set; }
        public string 帳號 { get; set; }
        public string 密碼 { get; set; }
        public string 名字 { get; set; }
        public string 手機 { get; set; }
        public string 註冊日期 { get; set; }
        public string 大頭貼 { get; set; }
        public int 點數 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<旅程包> 旅程包 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<提問> 提問 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<評級> 評級 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<圖片> 圖片 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<文章> 文章 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hashtag> Hashtag { get; set; }
    }
}
